algo = input('Digite algo:')
print('Está em letras maiusculas? ',algo.isupper())
print('Possui letras do alfabeto? ',algo.isalpha())
print('É alpha númerico? ',algo.isalnum())
print('É um número? '.algo.isnumeric())
