algo = input('Digite algo: ')
print('o tipo primitivo é: ', type(algo))
print('Está em letra maiúscula? ', algo.isupper())
print('Tem letras do alphabeto? ', algo.isalpha())
print('É alpha-numérico? ', algo.isalnum())
print('É um número? ', algo.isnumeric())
print('Está em letras minúsculas? ', algo.islower())
print('Só tem espaços? ', algo.isspace())
print('Está capitalizada? ', algo.istitle())